version: "3.9"
services:
  mysql:
    image: docker-public.docker.devstack.vwgroup.com/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=users_service
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080
      - SERVER_RUN_MODE=dev
      - RATELIMITER_REQUESTS_COUNT=10
      - RATELIMITER_ENABLED=false
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - DATABASE_URL=user:password@tcp(mysql:3306)/users_service
    depends_on:
      - mysql